package com.control;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.Configuration;

import com.to.Player;

public class HibernateMain {
	
	public static void main(String[] args) {
		
		
		try {
			Configuration configuration = new Configuration().configure();
			configuration.addAnnotatedClass(com.to.Player.class);
			StandardServiceRegistryBuilder builder = new StandardServiceRegistryBuilder()
					.applySettings(configuration.getProperties());
			
			SessionFactory sessionFactory = configuration.buildSessionFactory(builder.build());
			
			Session session = sessionFactory.openSession();
			Transaction transaction = session.beginTransaction();
//================Insert===============			
			//Player p1=new Player(1,"Virat","team1",23);
			//Player p2 = new Player(2,"ghadiyali","team2",30);
			//session.save(p1);
			//session.save(p2);
			
//===============select a player with Id 1==============
			
//			Player p =session.get(Player.class, 1); 
//			System.out.println("The Details : "+p);
//			
//==================update===============
//			p.setAge(90);
//			p.setPlayerName("kohli");
			
//===============delete==================
			//session.delete(p);
			
//================AutoGeneratedvalue=============
			Player p1=new Player("Virat","team1",23);
			Player p2 = new Player("ghadiyali","team2",30);
			session.save(p1);
			session.save(p2);
			
			transaction.commit();
			session.close();
		}catch(Exception e) {
			System.out.println(e.getMessage());
		}
		
		
		
	}

}
